name: Display information about GitHub Actions CPU architecture
on: push
jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
        name: [1...50]
    name: Display lscpu - ${{matrix.name}}
    runs-on: ${{matrix.runs-on}}
    steps: 
      - name: ubuntu
        if: runner.os == 'Linux'
        run: lscpu
      - name: windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: systeminfo
      - name: mac
        if: runner.os == 'macOS'
        run: system_profiler SPHardwareDataType
